---
#------------------------------------------------------#
#NOTE: Please fill the value with a space between ":" and the value.
#Example-   `system_user_name: ubuntu`

s3_access_key:
s3_secret_key:
git_branch: